apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blockchain-connector-polygon-testnet
spec:
  values:
    deployment:
      env:
        APPLICATION_NAME: blockchain-connector-polygon-testnet
        INSTANCE_CHAINS: POLYGON_TESTNET
