apiVersion: apps/v1
kind: Deployment
metadata:
  name: uta-transactions-history-pg
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uta-transactions-history-pg
  template:
    metadata:
      labels:
        app: uta-transactions-history-pg
    spec:
      serviceAccountName: transactions-history
      containers:
        - name: psql
          image: postgres
          command: ["sh"]
          args: ["-c", "tail -f /dev/null"]
          env:
            - name: PGPASSWORD
              value: "1"
            - name: POSTGRES_USER
              value: "pg-uta-transactions-history@dev-uta-ng-stack.iam"
            - name: POSTGRES_DATABASE
              value: "uta_transactions_history"
            - name: POSTGRES_HOST
              value: '127.0.0.1'
            - name: POSTGRES_PORT
              value: '5000'
        - name: csql
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
          args:
            - >-
              dev-uta-ng-stack:europe-west4:dev-uta-ng-stack-postgres?auto-iam-authn=true&port=5000&private-ip=true
          ports:
            - containerPort: 9801
              protocol: TCP
          env:
            - name: CSQL_PROXY_HTTP_PORT
              value: '9801'
            - name: CSQL_PROXY_HTTP_ADDRESS
              value: 0.0.0.0
            - name: POSTGRES_HOST
              value: '127.0.0.1'
            - name: POSTGRES_PORT
              value: '5000'
      restartPolicy: Always
