apiVersion: v1
kind: Secret
metadata:
    name: rates-publisher-secret
    namespace: apps
stringData:
    PROVIDERS_OER_CONFIG_APP_ID: ENC[AES256_GCM,data:6lZ66RLn1l+ehfrhFNHixyQXIy+SIcPHy0s9+Z/IMmM=,iv:MY3SU/6cPl9BE+RRl5+/vYk5+lWiQG2XovTBre4CD4I=,tag:DVhuMZ2wgtJwNrYHiT0Cpw==,type:str]
    PROVIDERS_COINMARKETCAP_CONFIG_API_KEY: ENC[AES256_GCM,data:tfhvDZmIMkv1JzJkq6OvWR3LmSh0IkB0vSCvB3RYAX/Q+hsM,iv:pyDieNE/kSsFpgJ38rriQt1QSrvinvZFNb4y3z6tf98=,tag:xo85p2zNdiMDdXVs5D6opg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/stage-uta-stack/locations/global/keyRings/stage-uta-stack-sops/cryptoKeys/stage-uta-stack-sops-default
          created_at: "2025-11-06T13:12:58Z"
          enc: CiQAYOVv4MlaeT3ebbsWWliqadCMh6ILSUeTF6+ttv5ZzfrkhrASSQAOvymTP9fUEyunjsdyKZm+N9J/uP8uZgH45VkCZ4h/xlwuVevUreL1RkR7QIYI/e+gA/J+ejjncZvevOdxoThS3Z6tRJ2mMJ0=
    lastmodified: "2025-11-06T13:12:59Z"
    mac: ENC[AES256_GCM,data:Pe5yE9B7LwdLFrNliodkxfGtSuMSPM5mEwhhioxQvwLLBo3V5mHW1hO/NCoNAwPSr4SnszUIcIGp4m6fd2ZZyWt/jFwUfD34zvnurguLDV2AggUWRXMAKZgvBSCH5qnG8pJ4HhI12srGIlQf/+Y9gkYz4jTZ8fL0i4AzP0oODBw=,iv:1nPN2iwGvrI3tEQZmfdLqp8t5b6S8pWSA8UoTjHUsgw=,tag:lt1T1ZY/D63rtujAMRozbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
