apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: widgets
  namespace: apps
spec:
  interval: 1m
  chart:
    spec:
      chart: app
      version: "1.21.0"
      sourceRef:
        kind: HelmRepository
        name: default
      interval: 5m
  values:
    global:
      envSecretNames:
        - "common-secret"
      envConfigMapNames:
        - "common-env-cm"
    deployment:
      replicaCount: 1
      strategy:
        type: Recreate
      image:
        tag: "2.52.0-204-ged8cc015" # {"$imagepolicy": "apps:widgets-image-policy:tag"}
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
      containerPort: 3000
      env:
        APPLICATION_NAME: widgets
        HTTP_URL: https://admin-{{ .Values.env }}.utorg.com/api/widgets
        REDIS_HOST: redis-master.uta-redis.svc.cluster.local
        REDIS_PORT: "6379"
        NODE_OPTIONS: "--max-old-space-size=1600"
        TYPEORM_MIGRATIONS: "true"
        TYPEORM_SYNCHRONIZE: "false"
        HTTP_DOCS_PATH: api-docs
        COINMARKETCAP_TOKEN_QUOTE_UPDATE_PERIOD_MIN: "60"
        COINMARKETCAP_TOKEN_ALL_TIME_UPDATE_PERIOD_MIN: "60"
