apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blockchain-connector-litecoin
spec:
  values:
    deployment:
      env:
        APPLICATION_NAME: blockchain-connector-litecoin
        INSTANCE_CHAINS: LITECOIN

