apiVersion: v1
kind: Secret
metadata:
    name: common-secret
    namespace: apps
stringData:
    POSTGRES_CASBIN_DATABASE: ENC[AES256_GCM,data:NytPHl1og9J2SA==,iv:LICVkjur3JDen1DNgUtPQ7rg96IAD6HMKxcbIli3ijc=,tag:b/6JUHwdHEJvc0SwROlcRg==,type:str]
    POSTGRES_CASBIN_PASSWORD: ENC[AES256_GCM,data:6BTKUSH/3xU11aeI3LYsJQ==,iv:uRr+Rk9bgsMJc6x4oK77DQU2bAhlwNdxe6Q/Loto2n0=,tag:6+95P7GEP70LJkDmdRdFcg==,type:str]
    POSTGRES_CASBIN_USER: ENC[AES256_GCM,data:15xX37f1cqWP/w==,iv:Bz6W3QDBO/gh9fJpP0DxIVW1ojDFPAAlebwD+dEKVic=,tag:BtoVoMs2RAHqbu3IjUO+AQ==,type:str]
    BLOCKCHAIN_TESTNET: ENC[AES256_GCM,data:8GNl3mA=,iv:9j+rcqiBMQpnzBNIVLbOyToQEp715ziYysWpRcsC/rY=,tag:8c3qarhdm5CV38URzCHzBg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dev-uta-ng-stack/locations/global/keyRings/dev-uta-ng-stack-sops/cryptoKeys/dev-uta-ng-stack-sops-default
          created_at: "2025-05-07T05:33:12Z"
          enc: CiQA32Iz2gj3HwfBTqb3AtfWptZfUsCc2UC76/eMIp6Um/7cEVQSSACn9+vxk9d6kzeuH6osHCyWaRjf/fYyJc3rY6zK3bXqvWwF39UsR5Nx4LB4BRDoI6wkhQsTUqVz7dqniRZ3iqfdAyvS4SaRuA==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-07T06:01:13Z"
    mac: ENC[AES256_GCM,data:WKtzqiAia7o2kQFngSuy+q2PsFJW1xkZTHZU/LFlJNGLdczHinuJEn2LyPdz04j9QI+5aGp8600S49d5qZc1WcB9eXTDbdPz+gJv8YGLWXIeb7a1Ng7yf2UeARgJJwEqXF7Ykx5W/FUNlhSQjQXthAWELosVSPnw8veILFXlIo4=,iv:qyT+nL5OHHq4uPnt/I60hRRADycrx1Cuko8efXjd15w=,tag:7MpHaIlStxmIHgCrF2MlZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
