apiVersion: v1
kind: Secret
metadata:
    name: sse-gateway-secret
    namespace: apps
stringData:
    NATS_PUBLIC_KEY: ENC[AES256_GCM,data:/jgl3TLtshG/gH52JEDDh9gKvjkUSFoJ5wpNM7vJnYDgHRwUbd8vogPk5W25pNCmFcFDVanddlw=,iv:6jHo7IHjuMGRLROoCQMlpq41pFEkOoqOKFQqZqUF6Oc=,tag:GUxDfQHfDQHaBqgrGsqgsA==,type:str]
    NATS_SECRET_KEY: ENC[AES256_GCM,data:9VFJyogXXE/3NxK4oclSu+gzk/f5oSuvPQ/ChqU7/8DxS3vkaM16OwBfJAHBbfu7zsyif8aFpMgQgA==,iv:blIjzyBDqhkp1gehdBsz3vb5o8jPKDoTH4+8PrBtOYo=,tag:CZpfPELGyUbHhW9qqO45FA==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/stage-uta-stack/locations/global/keyRings/stage-uta-stack-sops/cryptoKeys/stage-uta-stack-sops-default
          created_at: "2025-09-03T05:54:05Z"
          enc: CiQAYOVv4Eg7oE9glX+caohIRdJRHZRUphAJs2sJ/E7ycSzzYeASSQAOvymTlY2cysZkvL+MDAsNYwe4NsHift+xDG9+g5tvQxqBxFvVRHZSFKWDLyqo5x5F4KbchVKt3/dQ8wo6mT32jVa3TeInhoM=
    lastmodified: "2025-09-03T05:54:05Z"
    mac: ENC[AES256_GCM,data:pbFTRM7sI7FGonlOC4oBbiXUWSmRIpynpne9bZed3oZCaTsNcoGA+JyTBX0bNNLHyTknMMEGCzuoZTyJyUbd6XqldL7Y48u7sStIqGGeoHr4rrJGhX9V5iPnsgkISvr2R66G5B0C83h+TgARq/iJv/kiCd8Ub2gmyQALU45Vx9o=,iv:GpHp0XS4TFKxGSkYjnOaKajeVJgrD/FYT7894ItP2nI=,tag:3ndSpqjUu/ZvDfvTevUKFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
