apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: address-validation
  namespace: apps
spec:
  interval: 1m
  chart:
    spec:
      chart: app
      version: "1.19.1"
      sourceRef:
        kind: HelmRepository
        name: default
      interval: 5m
  values:
    global:
      envSecretNames:
        - "common-secret"
      envConfigMapNames:
        - "common-env-cm"
    deployment:
      replicaCount: 1
      containerPort: 3000
      env:
        APPLICATION_NAME: address-validation
        HTTP_URL: https://admin-dev.utorg.com/api/address-validation
        HTTP_DOCS_PATH: api-docs
        NODE_OPTIONS: "--max-old-space-size=1600"
        TYPEORM_SYNCHRONIZE: "false"
      image:
        repository: "europe-west4-docker.pkg.dev/dev-uta-ng-stack/dev-uta-ng-stack-cr/address-validation" # {"$imagepolicy": "apps:address-validation-image-policy:name"}
        tag: "2.52.0-125-gfc6d8af2" # {"$imagepolicy": "apps:address-validation-image-policy:tag"}
      resources:
        requests:
          cpu: "10m"
          memory: "600Mi"
        limits:
          cpu: "1"
          memory: "2Gi"
