apiVersion: v1
kind: Secret
metadata:
    name: sse-gateway-secret
    namespace: apps
stringData:
    NATS_PUBLIC_KEY: ENC[AES256_GCM,data:lp8WZc4gSUR8e6ra/5sTHW/LUSKoZLzLGnkv5KSbMgHb2/YX+NORG4jr4IEtHTqziVipqS+cUKk=,iv:FJW3875xOK+pF0SDTWB+tc/XVvU/PSDoEYCKS3NnZl4=,tag:2N1+/GBGZ7BQBUB9L6hxyA==,type:str]
    NATS_SECRET_KEY: ENC[AES256_GCM,data:sJ6Ys/SmRvngyMVM87T6j+i0lIlm2YRL49iNEWG8N4liu0NlMCET1jJ8hAi9n0igevSdCI6LWXHQNQ==,iv:GAuDDzlDv9yDkXAD33U5G2K6FnzbiRDoGUS5BY6heE0=,tag:RPn6Xw4B3bKHLNAW4BOQaw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dev-uta-ng-stack/locations/global/keyRings/dev-uta-ng-stack-sops/cryptoKeys/dev-uta-ng-stack-sops-default
          created_at: "2025-05-20T23:57:12Z"
          enc: CiQA32Iz2m59m7kcAXY5lDnTBgV9+3IlAH5wXh3RotGu++dAMWsSSQCn9+vxPVFdTSyY0z53S3CbyxsjSFq88Zq/vMwrCo0AgKYF1I/QEYqJu8w5u4RjsyfqlsQ9ArBauG8OhEqqkxxgo1diEmZO4w4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-20T23:57:13Z"
    mac: ENC[AES256_GCM,data:rIu7DHszWfwWMIY/xbwHnA9KrEE9tVDqMtLoqDa4HrDNG+yYMSaEL1TUOPlpt3qgWUuv8vFBwKRGmRMML0qhq4R+WwSoaIw4JgHMDCSKgNPTBaxpAkfS7q0VQn0CP01Bp0IFvXj1N5Pif+lYsHKB5F6JN2tpiS6VJnYl25FGXh4=,iv:Sbdvi6yMN32rqUQvlNR/7JA/aOhwxm3Ytzg8c+Mf/rY=,tag:aT0WzoGybtux/nsD0L8etg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
