# Staging Environment Defaults - UTA Testing
# Environment-specific overrides for staging branches

environment: staging

# Docker publishing
docker:
  enabled: false
  push: false
  repository: github-testing-stage-cr-v2

# Maven Repository Configuration (Staging)
maven:
  pull_repo_url: "artifactregistry://europe-west4-maven.pkg.dev/zerohub-core-0/github-testing-stage-mvn"
  release_repo_url: "artifactregistry://europe-west4-maven.pkg.dev/zerohub-core-0/github-testing-stage-mvn"
  snapshot_repo_url: "artifactregistry://europe-west4-maven.pkg.dev/zerohub-core-0/github-testing-stage-mvn"

# NPM Registry Configuration (Staging)
npm:
  scope: "@ut"
  registries:
    - scope: "@ut"
      project_id: zerohub-core-0
      region: europe-west4
      repository: github-testing-stage-npm-v2
    # @ut-libs packages are shared dependencies - pull from shared registry
    - scope: "@ut-libs"
      project_id: zerohub-core-0
      region: europe-west4
      repository: github-testing-npm-v2
