apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: back-office
  namespace: apps
spec:
  interval: 1m
  chart:
    spec:
      chart: app
      version: "1.21.2"
      sourceRef:
        kind: HelmRepository
        name: default
      interval: 5m
  values:
    global:
      envSecretNames:
        - "common-secret"
      envConfigMapNames:
        - "common-env-cm"
    deployment:
      replicaCount: 1
      containerPort: 3000
      env:
        APPLICATION_NAME: back-office
        HTTP_URL: https://admin-{{ .Values.env }}.utorg.com/api/backoffice
        HTTP_DOCS_PATH: api-docs
        NODE_OPTIONS: "--max-old-space-size=1600"
        TYPEORM_SYNCHRONIZE: "false"
      image:
        tag: "2.91.0-1-g5fe7cec5" # {"$imagepolicy": "apps:back-office-image-policy:tag"}
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
        limits:
          cpu: "500m"
          memory: "2Gi"
    virtualServicesHttp:
      - name: docs
        enabled: true
        gateway: "istio-ingress/uta-{{ .Values.env }}-utorg-com"
        host: "admin-{{ .Values.env }}.utorg.com"
        prefix: "/api/backoffice/api-docs"
        rewrite:
          uri: "/api-docs/"
      - name: default
        enabled: true
        gateway: "istio-ingress/uta-{{ .Values.env }}-utorg-com"
        host: "admin-{{ .Values.env }}.utorg.com"
        prefix: "/api/backoffice"
        enablePathRewriteToRoot: true
