apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: address-book
  namespace: apps
spec:
  interval: 1m
  chart:
    spec:
      chart: app
      version: "1.21.0"
      sourceRef:
        kind: HelmRepository
        name: default
      interval: 5m
  values:
    global:
      envSecretNames:
        - "common-secret"
      envConfigMapNames:
        - "common-env-cm"
    deployment:
      replicaCount: 1
      containerPort: 3000
      env:
        APPLICATION_NAME: address-book
        HTTP_URL: https://admin-{{ .Values.env }}.utorg.com/api/address-book
        HTTP_DOCS_PATH: api-docs
        POSTGRES_DATABASE: uta_address_book
        TYPEORM_MIGRATIONS: "true"
        TYPEORM_SYNCHRONIZE: "false"
        NODE_OPTIONS: "--max-old-space-size=1600"
      image:
        tag: "2.77.0-6-g4072a6c8" # {"$imagepolicy": "apps:address-book-image-policy:tag"}
      resources:
        requests:
          cpu: "10m"
          memory: "600Mi"
        limits:
          cpu: "500m"
          memory: "2Gi"
      cloudsql:
        enabled: true
      workloadIdentityMapping:
        enabled: true
        serviceAccountName: "pg-uta-address-book"
    virtualServicesHttp:
      - name: docs
        enabled: true
        gateway: "istio-ingress/uta-{{ .Values.env }}-utorg-com"
        host: "admin-{{ .Values.env }}.utorg.com"
        prefix: "/api/address-book/api-docs"
        rewrite:
          uri: "/api-docs/"
      - name: default
        enabled: true
        gateway: "istio-ingress/uta-{{ .Values.env }}-utorg-com"
        host: "admin-{{ .Values.env }}.utorg.com"
        prefix: "/api/address-book"
        enablePathRewriteToRoot: true
