apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: address-book
  namespace: apps
spec:
  interval: 1m
  chart:
    spec:
      chart: app
      version: "1.19.1"
      sourceRef:
        kind: HelmRepository
        name: default
      interval: 5m
  values:
    global:
      envSecretNames:
        - "common-secret"
      envConfigMapNames:
        - "common-env-cm"
    deployment:
      replicaCount: 1
      containerPort: 3000
      env:
        APPLICATION_NAME: address-book
        HTTP_URL: https://admin-dev.utorg.com/api/address-book
        HTTP_DOCS_PATH: api-docs
        POSTGRES_USER: pg-uta-address-book@dev-uta-ng-stack.iam
        POSTGRES_DATABASE: uta_address_book
        TYPEORM_MIGRATIONS: "true"
        TYPEORM_SYNCHRONIZE: "false"
        NODE_OPTIONS: "--max-old-space-size=1600"
      image:
        repository: "europe-west4-docker.pkg.dev/dev-uta-ng-stack/dev-uta-ng-stack-cr/address-book" # {"$imagepolicy": "apps:address-book-image-policy:name"}
        tag: "2.52.0-204-ged8cc015" # {"$imagepolicy": "apps:address-book-image-policy:tag"}
      resources:
        requests:
          cpu: "10m"
          memory: "600Mi"
        limits:
          cpu: "500m"
          memory: "2Gi"
      cloudsql:
        enabled: true
        connectionString: "dev-uta-ng-stack:europe-west4:dev-uta-ng-stack-postgres"
      workloadIdentityMapping:
        enabled: true
        project: "dev-uta-ng-stack"
        serviceAccountName: "pg-uta-address-book"
    virtualServicesHttp:
      - name: docs
        enabled: true
        gateway: "istio-ingress/uta-dev-utorg-com"
        host: "admin-dev.utorg.com"
        prefix: "/api/address-book/api-docs"
        rewrite:
          uri: "/api-docs/"
      - name: default
        enabled: true
        gateway: "istio-ingress/uta-dev-utorg-com"
        host: "admin-dev.utorg.com"
        prefix: "/api/address-book"
        enablePathRewriteToRoot: true
