apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blockchain-connector-bitcoin
spec:
  values:
    deployment:
      env:
        APPLICATION_NAME: blockchain-connector-bitcoin
        INSTANCE_CHAINS: BITCOIN
