apiVersion: v1
kind: Secret
metadata:
    name: wallet-manager-secret
    namespace: apps
stringData:
    COINMARKETCAP_KEY: ENC[AES256_GCM,data:a4iw246WBTpcvnPHqgQuXPhahhbp5IN8okKm/Mp9VTwiIz7d,iv:DOq9B3lpwRX9XC/Nt6A49ZM7G5ADue3k+PqJ1+sdNRQ=,tag:NoNyT0iXBLSYyJRr+04rkw==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/stage-uta-stack/locations/global/keyRings/stage-uta-stack-sops/cryptoKeys/stage-uta-stack-sops-default
          created_at: "2025-09-03T05:54:06Z"
          enc: CiQAYOVv4BVf8AzciuIwvi/il7i6o0ndQvrHtTpLt75uRfRipcUSSQAOvymTUqreq581bCNvsfPDtFfx/DWkarkYgs0OBppgh8Qrn4J5Js0yIlhOm6ce3pVl9FJ+C9bl1UHfmVOe7rgffKG2xKonryE=
    lastmodified: "2025-09-03T05:54:06Z"
    mac: ENC[AES256_GCM,data:eP2zHj8onszAB0ZdWZw9acbMdtAfc/GuINy0TRSa4FqzLbWhhBdTe5fvlxg4At/KY9E4r+CNnqUP76IGQJpwOG0PBvGdenN9P86/Eqo+qCUAxzwiPb2ccVPbQlOCkv25IC7vRoKEnaFfvJQVh8ivp1jVxKCBAniDtwUHBEXNihU=,iv:5zmKxEkzE7+SGrqByE86JJON5qz/HPWNfo3sv6lLKOA=,tag:m6+OQB7kS137AslzWiLddg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
