apiVersion: v1
kind: Secret
metadata:
    name: identity-manager-secret
    namespace: apps
stringData:
    NATS_TOKEN_SETTINGS_MQTT_ACCOUNT_SEED: ENC[AES256_GCM,data:xBlffL0ADZdAjo9QMWdhUkeSqXrCwvOV5o9cUzkHwRqlZ7Q8xAKAc7Qv43r13JbKbwtvQWpwPmGV/w==,iv:kZ0UxYSub+ndCLbpGhYEskQG8L7cnCOu7mAGE/AH1hY=,tag:WXYe27BvsN6FH3U0PimPHA==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/stage-uta-stack/locations/global/keyRings/stage-uta-stack-sops/cryptoKeys/stage-uta-stack-sops-default
          created_at: "2025-09-03T05:54:10Z"
          enc: CiQAYOVv4KsGAX4BrGC48K+5wdCHhrXzC44YPCpP56T3FM5GQCQSSQAOvymTthGD/A/S8Zr5eFE1S5uU7QnTyx+f/+u38fZtqHChwLvimNuVB6SxRd31Sn4kgzV3/kCsaKAU1fSZMfuunWUVy1ugQ7M=
    lastmodified: "2025-09-03T05:54:10Z"
    mac: ENC[AES256_GCM,data:0zp47Ao9mAGuFk3BMryjVt6AorNAWCAufwb5aTRJIGf+whMsM+akAm28PeY7su3EivEdybpZY1wUlJjCyrj00yytFeZ9n02fwL+mezh1b20LuDYfZ5z/2tXaGNYQKWs5p/Us+cshVfje4X2V4t77aARirF2pV58ae/f133LcQLw=,iv:f5qsyyu0hu9zgQ15YF50FEuKPWwiYNnfePdt0X4DffA=,tag:ucoqQ0SxMa7ai9oTk2pAsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
