apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ramp-api
  namespace: apps
spec:
  interval: 1m
  chart:
    spec:
      chart: app
      version: "1.18.1"
      sourceRef:
        kind: HelmRepository
        name: default
      interval: 5m
  values:
    global:
      envSecretNames:
        - "common-secret"
        - "ramp-api-secret"
      envConfigMapNames:
        - "common-env-cm"
    deployment:
      replicaCount: 0
      strategy:
        type: Recreate
      image:
        repository: "europe-west4-docker.pkg.dev/dev-uta-ng-stack/dev-uta-ng-stack-cr/ramp-api" # {"$imagepolicy": "apps:ramp-api-image-policy:name"}
        tag: "latest" # {"$imagepolicy": "apps:ramp-api-image-policy:tag"}
      resources:
        limits:
          cpu: "500m"
          memory: "2Gi"
      containerPort: 3000
      cloudsql:
        enabled: true
        connectionString: "dev-uta-ng-stack:europe-west4:dev-uta-ng-stack-postgres"
      workloadIdentityMapping:
        enabled: true
        project: "dev-uta-ng-stack"
        serviceAccountName: "pg-uta-api"
      env:
        APPLICATION_NAME: ramp-api
        HTTP_URL: https://app-dev.utorg.com/ramp-api
        NODE_OPTIONS: "--max-old-space-size=1600"
        TYPEORM_MIGRATIONS: "true"
        TYPEORM_SYNCHRONIZE: "false"
        HTTP_DOCS_PATH: api-docs
    virtualServicesHttp:
      - enabled: true
        name: docs
        gateway: "istio-ingress/uta-dev-utorg-com"
        host: "app-dev.utorg.com"
        prefix: "/ramp-api/api-docs"
        rewrite:
          uri: "/api-docs"
      - enabled: true
        name: default
        gateway: "istio-ingress/uta-dev-utorg-com"
        host: "app-dev.utorg.com"
        prefix: "/ramp"
        rewrite:
          uri: "/ramp"
