apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api
  namespace: apps
spec:
  interval: 1m
  chart:
    spec:
      chart: app
      version: "1.18.1"
      sourceRef:
        kind: HelmRepository
        name: default
      interval: 5m
  values:
    global:
      envSecretNames:
        - "common-secret"
      envConfigMapNames:
        - "common-env-cm"
    deployment:
      replicaCount: 0
      containerPort: 3000
      env:
        APPLICATION_NAME: api
        HTTP_URL: https://app-dev.utorg.com/api
        HTTP_DOCS_PATH: api-docs
        NATS_DEBUG: "false"
        NODE_OPTIONS: "--max-old-space-size=1600"
        TYPEORM_SYNCHRONIZE: "false"
        POSTGRES_USER: pg-uta-api@dev-uta-ng-stack.iam
        POSTGRES_DATABASE: uta_api
      image:
        repository: "europe-west4-docker.pkg.dev/dev-uta-ng-stack/dev-uta-ng-stack-cr/api" # {"$imagepolicy": "apps:api-image-policy:name"}
        tag: "2.52.0-125-gfc6d8af2" # {"$imagepolicy": "apps:api-image-policy:tag"}
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
        limits:
          cpu: "500m"
          memory: "2Gi"
      cloudsql:
        enabled: true
        connectionString: "dev-uta-ng-stack:europe-west4:dev-uta-ng-stack-postgres"
      workloadIdentityMapping:
        enabled: true
        project: "dev-uta-ng-stack"
        serviceAccountName: "pg-uta-api"
    virtualServicesHttp:
      - name: docs
        enabled: true
        gateway: "istio-ingress/uta-dev-utorg-com"
        host: "app-dev.utorg.com"
        prefix: "/api/api-docs"
        rewrite:
          uri: "/api-docs/"
      - name: default
        enabled: true
        gateway: "istio-ingress/uta-dev-utorg-com"
        host: "app-dev.utorg.com"
        prefix: "/api"
        enablePathRewriteToRoot: true
