apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: documentation
  namespace: apps
spec:
  interval: 1m
  chart:
    spec:
      chart: app
      version: "1.21.2"
      sourceRef:
        kind: HelmRepository
        name: default
      interval: 5m
  values:
    global:
      envSecretNames:
        - "common-secret"
      envConfigMapNames:
        - "common-env-cm"
    deployment:
      startupProbe:
        enabled: false
      replicaCount: 1
      strategy:
        type: Recreate
      image:
        tag: "2.52.0-204-ged8cc015" # {"$imagepolicy": "apps:documentation-image-policy:tag"}
      resources:
        limits:
          cpu: "500m"
          memory: "2Gi"
      containerPort: 3000
      cloudsql:
        enabled: false
      workloadIdentityMapping:
        enabled: false
      env:
        APPLICATION_NAME: documentation
        HTTP_PORT: "3000"
        DOCUMENTS: |
          {
            "address-book": "https://admin-{{ .Values.env }}.utorg.com/api/address-book/api-docs/json",
            "api": "https://app-{{ .Values.env }}.utorg.com/api/api-docs/json",
            "backoffice": "https://admin-{{ .Values.env }}.utorg.com/api/backoffice/api-docs/json",
            "balance-manager": "https://admin-{{ .Values.env }}.utorg.com/api/balance-manager/api-docs/json",
            "blockchain-connector": "https://admin-{{ .Values.env }}.utorg.com/api/blockchain-connector/api-docs/json",
            "blockchain-info": "https://admin-{{ .Values.env }}.utorg.com/api/blockchain-info/api-docs/json",
            "blockchain-watcher": "https://admin-{{ .Values.env }}.utorg.com/api/blockchain-watcher/api-docs/json",
            "currency-service": "https://admin-{{ .Values.env }}.utorg.com/api/currency-service/api-docs/json",
            "dead-letter": "https://admin-{{ .Values.env }}.utorg.com/api/dead-letter/api-docs/json",
            "identity-manager": "https://admin-{{ .Values.env }}.utorg.com/api/identity-manager/api-docs/json",
            "notifications": "https://app-{{ .Values.env }}.utorg.com/notifications/api-docs/json",
            "ramp-api": "https://app-{{ .Values.env }}.utorg.com/ramp-api/api-docs/json",
            "rates": "https://admin-{{ .Values.env }}.utorg.com/api/rates/api-docs/json",
            "rates-publisher": "https://admin-{{ .Values.env }}.utorg.com/api/rates-publisher/api-docs/json",
            "stat-service": "https://admin-{{ .Values.env }}.utorg.com/api/stat-service/api-docs/json",
            "stories": "https://admin-{{ .Values.env }}.utorg.com/api/stories/api-docs/json",
            "transactions-history": "https://admin-{{ .Values.env }}.utorg.com/api/transactions-history/api-docs/json",
            "swaps": "https://admin-{{ .Values.env }}.utorg.com/api/swaps/api-docs/json",
            "wallet-manager": "https://admin-{{ .Values.env }}.utorg.com/api/wallet-manager/api-docs/json",
            "fee-service": "https://admin-{{ .Values.env }}.utorg.com/api/fee-service/api-docs/json",
            "transaction-sender": "https://admin-{{ .Values.env }}.utorg.com/api/tx-sender/api-docs/json"
          }
    virtualServicesHttp:
      - enabled: true
        name: default
        gateway: "istio-ingress/uta-{{ .Values.env }}-utorg-com"
        host: "docs-{{ .Values.env }}.utorg.com"
        prefix: "/"
