# UTA Testing Project - Service Defaults
# This file defines project-level defaults for all UTA testing services
# Testing mode: No artifacts published, tests only

# Git tag prefix for versioning
git_tag_prefix: "uta-testing@"

# GCP Configuration
gcp:
  project_id: zerohub-core-0
  region: europe-west4
  workload_identity_provider: "projects/360996291169/locations/global/workloadIdentityPools/testing-utp-stack/providers/github"
  service_account: "github-actions@zerohub-core-0.iam.gserviceaccount.com"

# Docker Registry Configuration
# Registry URLs are specified in environment-specific configs (envs/*/):
#   - envs/dev/_defaults.yaml: github-testing-dev-cr
#   - envs/stage/_defaults.yaml: github-testing-stage-cr
#   - envs/prod/_defaults.yaml: github-testing-prod-cr
docker:
  registry_host: europe-west4-docker.pkg.dev
  enabled: false  # Testing mode disables Docker publishing

# Maven Repository Configuration
# Registry URLs are specified in environment-specific configs (envs/*/)
maven: {}

# NPM Registry Configuration
# Registry URLs are specified in environment-specific configs (envs/*/)
npm:
  scope: "@ut"

# Build defaults
build:
  timeout_minutes: 20
  skip_tests: false
