# uta-backend-testing Service Configuration
# UTA backend monorepo - isolated testing repository - no artifacts published

service_id: uta-backend-testing
type: nestjs
enabled: true

build:
  timeout_minutes: 20

# Docker enabled for testing - images built to testing registry but not deployed
docker:
  enabled: true
  image_name: uta-backend-testing
  repository: github-testing-cr
  dockerfile: "./docker/actions/app.dockerfile"
  modules_dockerfile: "./docker/actions/modules.dockerfile"
  platforms: "linux/amd64"
  # Build args required by docker/actions/app.dockerfile
  # The 'app' arg is automatically set to the service name for matrix builds
  build_args:
    modules: "node:20-alpine"

# NPM registry for @ut-libs packages (production registry for shared libs)
npm:
  registries:
    - scope: "@ut-libs"
      project: "global-410306"
      repository: "npm"

# Monorepo Configuration
# uta-backend is a NestJS monorepo with apps/ directory structure
monorepo:
  enabled: true
  apps_path: "apps"
  libs_path: "libs"
  # List of apps that can be built (must match actual directory names in test repo)
  # Note: uta-backend-testing has different app names than production
  buildable_apps:
    - api
    - notifications
    - rates
  # Apps excluded from builds (test utilities, playgrounds, documentation)
  excluded_apps:
    - playground
    - stories
    - documentation

# Feature flags
features:
  dependency_submission: false
  auto_deploy: false

# Required secrets (reference only)
secrets:
  - GCP_PROJECT_ID
  - GLOBAL_GCP_SERVICE_ACCOUNT
  - GLOBAL_GCP_WORKLOAD_IDENTITY_PROVIDER

# Version bump disabled for all environments in testing
environments:
  develop:
    version_bump:
      enabled: false
  staging:
    version_bump:
      enabled: false
  master:
    version_bump:
      enabled: false
