# uta-backend-testing Service Configuration
# UTA backend monorepo - isolated testing repository - no artifacts published

service_id: uta-backend-testing
type: nestjs
enabled: true

build:
  timeout_minutes: 20

# Docker enabled for testing - images built to testing registry but not deployed
# NOTE: docker.repository is set in environment-specific configs (envs/*/_defaults.yaml)
docker:
  enabled: true
  image_name: uta-backend-testing
  dockerfile: "./docker/actions/app.dockerfile"
  modules_dockerfile: "./docker/actions/modules.dockerfile"
  platforms: "linux/amd64"
  # Build args required by docker/actions/app.dockerfile
  # The 'app' arg is automatically set to the service name for matrix builds
  build_args:
    modules: "node:20-alpine"

# Monorepo Configuration
# uta-backend is a NestJS monorepo with apps/ directory structure
monorepo:
  enabled: true
  apps_path: "apps"
  # List of apps that can be built (must match actual directory names in test repo)
  # Note: uta-backend-testing has different app names than production
  buildable_apps:
    - api
    - notifications
    - rates
  # Apps excluded from builds (test utilities, playgrounds, documentation)
  excluded_apps:
    - playground
    - stories
    - documentation
