apiVersion: v1
kind: Secret
metadata:
    name: common-secret
    namespace: apps
stringData:
    BLOCKCHAIN_TESTNET: ENC[AES256_GCM,data:94gQnCs=,iv:k+jtJzSRmyEMmIhYhBvff6jLpRboSLCwRznCPiWISAU=,tag:6KpbwJtZfLQpubAjl6/jWA==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/stage-uta-stack/locations/global/keyRings/stage-uta-stack-sops/cryptoKeys/stage-uta-stack-sops-default
          created_at: "2025-09-03T05:54:06Z"
          enc: CiQAYOVv4CF35txPsvbkudVokSYcFKxUApwCMyQ5HAE65scI9yUSSAAOvymTXfewhtL7wiLOimlpen8z0g5JxgslMt/kKvcDUdyjWAKZOE0NB5iufEC2YPOmXKi1U7N5Yzz1mbNShtMPwy4MhOUKUQ==
    lastmodified: "2025-09-03T05:54:07Z"
    mac: ENC[AES256_GCM,data:rUj1gkzRTbV+0YSgCu/40Jz1ZbJ2/BJjOUU4cehnBFuFbTJBYSNHE6kfDbapVry++iHjI7z/9Kt9Hm3VuvEFTcCvKzbyULSflLvW9t1P0Z5EQlRtrgvjWq/EP6uacbFFPme77u/67dosc7ZjS3eHHXhG54jD961h+86FBT9svkU=,iv:yHGCrayJdhTEgiGT5ex/C2SUCWkbmHZ1SJ4sv6/vDnw=,tag:GcSbFarCVSqo3lLmfJP8QA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
